<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ProjectStyle>SDK</ProjectStyle>
    <ChaosAnalyzers_CleanCode_Analyzer_TF>netstandard2.0</ChaosAnalyzers_CleanCode_Analyzer_TF>
  </PropertyGroup>

  <Import Project="ChaosFramework.Collections.props" />

  <ItemGroup>
    <Compile Include="source/**/*.cs" />
  </ItemGroup>

</Project>